name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...
      working-directory: ./src

    - name: Start mosquitto
      uses: namoshek/mosquitto-github-action@v1
      with:
        version: '1.6'
        ports: '11883:1883'
#        certificates: ${{ github.workspace }}/.ci/tls-certificates
#        config: ${{ github.workspace }}/.ci/mosquitto.conf
#        password-file: ${{ github.workspace}}/.ci/mosquitto.passwd
        container-name: 'mqtt'

    - name: Test
      run: go test -v ./...
      working-directory: ./src
