name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Mosquitto MQTT Broker in GitHub Actions
      uses: Namoshek/mosquitto-github-action@v1
#      with:
#        version: '1.6'
#        ports: '11883:1883'
##        certificates: ${{ github.workspace }}/.ci/tls-certificates
##        config: ${{ github.workspace }}/.ci/mosquitto.conf
##        password-file: ${{ github.workspace}}/.ci/mosquitto.passwd
#        container-name: 'mqtt'

    - name: Test
      run: go test -v ./...
      working-directory: ./src
